#ifndef QUERY_ERROR_H_
#define QUERY_ERROR_H_

#define INVALID_NTOTAL "INVALID_NTOTAL"
#define INVALID_DATA "INVALID_DATA"
#define EMPTY_DATA "EMPTY_DATA"
#define INVALID_DIMENSION "INVALID_DIMENSION"
#define MISSING_ARGUMENTS "MISSING_ARGUMENTS"
#define INVALID_TOPK "INVALID_TOPK"
#define INVALID_QTOTAL "INVALID_QTOTAL"
#define EMPTY_QUERIES "EMPTY_QUERIES"
#define INVALID_QUERIES "INVALID_QUERIES"
#define INVALID_IDS "INVALID_IDS"  
#define INVALID_RANGE "INVALID_RANGE"
#define INVALID_RECONFIG_FILEPATH "INVALID_RECONFIG_FILEPATH"
#define RELOAD_FAIL "RELOAD_FAIL"
#define READD_FAIL "READD_FAIL"
#define INVALID_NQ "INVALID_NQ"
#define INVALID_RADIUS "INVALID_RADIUS"
#define INVALID_DAYS "INVALID_DAYS"
#define NOTEXIST_INDEX "NOTEXIST_INDEX"

#define BAD_REQUEST "400"
#define OK "200"

#define ADD_SUCCESS "ADD_SUCCESS"
#define ADD_FAIL "ADD_FAIL"

#define SEARCH_SUCCESS "SEARCH_SUCCESS"
#define SEARCH_FAIL "SEARCH_FAIL"  

#define DELETE_SUCCESS "DELETE_SUCCESS"
#define DELETE_FAIL "DELETE_FAIL"

#define DELETERANGE_SUCCESS "DELETERANGE_SUCCESS"
#define DELETERANGE_FAIL "DELETERANGE_FAIL"

#define RECONFIG_SUCCESS "RECONFIG_SUCCESS"

#define SEARCH_RANGE_SUCCESS "SEARCH_RANGE_SUCCESS"
#define SEARCH_RANGE_FAIL "SEARCH_RANGE_FAIL"

#define SEARCHDAYS_SUCCESS "SEARCHDAYS_SUCCESS"
#define SEARCHDAYS_FAIL "SEARCHDAYS_FAIL"

#endif //QUERY_ERROR_H_
